name: consummo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter

  flutter_mobx: ^2.0.3+2
  flutter_modular: ^4.5.0
  mobx: ^2.0.6+1
  shared_preferences: ^2.0.12
  sqflite: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.7


flutter:

  uses-material-design: true
